run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - bodyclose
    - noctx

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
  goimports:
    local-prefixes: github.com/flicky/go-ecommerce-api

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
